management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  #服务端口号
  port: 8080

spring:
  profiles:
    active: dev
  jackson:
    #JSON的时间数据的时区
    time-zone: GMT+8

logging:
  level:
    org.mongodb.driver.protocol.command: DEBUG


